/* Generates a formal FOIA letter PDF using the same CDN-loaded jsPDF as the risk report. */

import type { JsPDFInstance } from "./pdfTypes";

type JsPDFConstructor = new (opts: { unit: string; format: string; orientation: string }) => JsPDFInstance;

function loadJsPDF(): Promise<JsPDFConstructor> {
  return new Promise((resolve, reject) => {
    const w = window as Window & { jspdf?: { jsPDF: JsPDFConstructor } };
    if (w.jspdf?.jsPDF) { resolve(w.jspdf.jsPDF); return; }
    const script = document.createElement("script");
    script.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
    script.onload = () => {
      const loaded = (window as Window & { jspdf?: { jsPDF: JsPDFConstructor } }).jspdf?.jsPDF;
      if (loaded) resolve(loaded); else reject(new Error("jsPDF not found after load"));
    };
    script.onerror = () => reject(new Error("Could not load jsPDF from CDN"));
    document.head.appendChild(script);
  });
}

const CHARCOAL = "#1A1614";
const BRICK    = "#A63D2F";
const GRAY     = "#7A6F65";
const BORDER   = "#D6CFC8";
const CELL_A   = "#F4EFE8";

const PAGE_W = 210;
const PAGE_H = 297;
const M      = 24;
const CW     = PAGE_W - M * 2;
const FOOT_Y = PAGE_H - 14;

function drawFooter(doc: JsPDFInstance, page: number, total: number) {
  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.3);
  doc.line(M, FOOT_Y - 3, PAGE_W - M, FOOT_Y - 3);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(GRAY);
  doc.text(
    "Generated by Plumbum · plumbum.io · Plumbum does not provide legal advice. This letter is a civic template based on standard public records request language.",
    M, FOOT_Y + 3,
  );
  doc.text(`Page ${page} of ${total}`, PAGE_W - M, FOOT_Y + 3, { align: "right" });
}

function drawHeader(doc: JsPDFInstance) {
  doc.setFillColor(CELL_A);
  doc.rect(0, 0, PAGE_W, 30, "F");

  doc.setFont("times", "bold");
  doc.setFontSize(16);
  doc.setTextColor(CHARCOAL);
  doc.text("Plumbum", M, 13);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(GRAY);
  doc.text("PUBLIC RECORDS REQUEST — LEAD SERVICE LINE INVENTORY", M, 19);

  doc.setDrawColor(BRICK);
  doc.setLineWidth(0.5);
  doc.line(M, 24, PAGE_W - M, 24);
}

function wrap(doc: JsPDFInstance, text: string, x: number, y: number, maxW: number, lh: number): number {
  const lines = doc.splitTextToSize(text, maxW);
  doc.text(lines, x, y);
  return y + lines.length * lh;
}

export async function generateFoiaLetterPdf(letterText: string, senderName: string): Promise<void> {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

  drawHeader(doc);
  let y = 36;

  // Letter body — render as monospaced-style paragraphs
  const paragraphs = letterText.split("\n");

  doc.setFont("courier", "normal");
  doc.setFontSize(10);
  doc.setTextColor(CHARCOAL);

  const lh = 5.2;

  for (const para of paragraphs) {
    if (y > FOOT_Y - 12) {
      drawFooter(doc, doc.getNumberOfPages(), doc.getNumberOfPages() + 1);
      doc.addPage();
      drawHeader(doc);
      y = 36;
      doc.setFont("courier", "normal");
      doc.setFontSize(10);
      doc.setTextColor(CHARCOAL);
    }

    if (para.trim() === "") {
      y += lh;
      continue;
    }

    // Highlight "Re:" line in brick red
    if (para.startsWith("Re:")) {
      doc.setFont("courier", "bold");
      doc.setTextColor(BRICK);
      y = wrap(doc, para, M, y, CW, lh);
      doc.setFont("courier", "normal");
      doc.setTextColor(CHARCOAL);
    } else {
      y = wrap(doc, para, M, y, CW, lh);
    }
    y += 1;
  }

  // Legal disclaimer box at bottom of last page
  if (y < FOOT_Y - 28) {
    y += 8;
    doc.setFillColor("#FDF8F2");
    doc.setDrawColor(BORDER);
    doc.setLineWidth(0.3);
    doc.rect(M, y, CW, 18, "FD");
    doc.setFont("helvetica", "italic");
    doc.setFontSize(7.5);
    doc.setTextColor(GRAY);
    wrap(
      doc,
      "Note: This is a civic template provided by Plumbum. It is not legal advice. You may wish to consult your state's FOIA statute for specific procedural requirements, including the correct form, fee schedule, and appeal process for your jurisdiction.",
      M + 4, y + 6, CW - 8, 4.5,
    );
  }

  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    drawFooter(doc, p, total);
  }

  const slug = senderName.trim().replace(/\s+/g, "-").toLowerCase() || "requester";
  doc.save(`foia-letter-${slug}-${new Date().toISOString().slice(0, 10)}.pdf`);
}
