/* Loads jsPDF from CDN at call-time so no npm install is required. */

interface JsPDFConstructor {
  new (opts: { unit: string; format: string; orientation: string }): JsPDFInstance;
}

interface JsPDFInstance {
  setFont(name: string, style: string): void;
  setFontSize(size: number): void;
  setTextColor(color: string): void;
  setDrawColor(color: string): void;
  setFillColor(color: string): void;
  setLineWidth(w: number): void;
  text(text: string | string[], x: number, y: number, opts?: Record<string, unknown>): void;
  getTextWidth(text: string): number;
  splitTextToSize(text: string, maxWidth: number): string[];
  line(x1: number, y1: number, x2: number, y2: number): void;
  rect(x: number, y: number, w: number, h: number, style?: string): void;
  roundedRect(x: number, y: number, w: number, h: number, rx: number, ry: number, style?: string): void;
  circle(x: number, y: number, r: number, style?: string): void;
  addPage(): void;
  setPage(p: number): void;
  getNumberOfPages(): number;
  save(filename: string): void;
}

function loadJsPDF(): Promise<JsPDFConstructor> {
  return new Promise((resolve, reject) => {
    const w = window as Window & { jspdf?: { jsPDF: JsPDFConstructor } };
    if (w.jspdf?.jsPDF) { resolve(w.jspdf.jsPDF); return; }
    const script = document.createElement("script");
    script.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
    script.onload = () => {
      const loaded = (window as Window & { jspdf?: { jsPDF: JsPDFConstructor } }).jspdf?.jsPDF;
      if (loaded) resolve(loaded); else reject(new Error("jsPDF failed to initialise"));
    };
    script.onerror = () => reject(new Error("Could not load jsPDF from CDN"));
    document.head.appendChild(script);
  });
}

// ── Palette ──────────────────────────────────────────────────────────────────
const BRICK    = "#A63D2F";
const AMBER    = "#C07A2A";
const GREEN    = "#4A7C59";
const CHARCOAL = "#1A1614";
const GRAY     = "#7A6F65";
const BORDER   = "#D6CFC8";
const CELL_A   = "#F4EFE8";
const CELL_B   = "#EDE8E2";

const PAGE_W   = 210;
const PAGE_H   = 297;
const M        = 20;        // margin
const CW       = PAGE_W - M * 2;  // content width
const FOOT_Y   = PAGE_H - 14;

function riskColor(level: string) {
  const l = level.toLowerCase();
  return l === "high" ? BRICK : l === "moderate" ? AMBER : GREEN;
}

function severityColor(s: string) {
  return s === "HIGH" ? BRICK : s === "MODERATE" ? AMBER : GREEN;
}

interface ParsedFactor { title: string; explanation: string; severity: "HIGH" | "MODERATE" | "LOW" }

function parseFactor(raw: string): ParsedFactor {
  const l = raw.toLowerCase();
  if (l.includes("pre-1986") || l.includes("pre 1986") || l.includes("built before"))
    return { title: "Pre-1986 Construction", severity: "HIGH", explanation: "Homes built before 1986 are significantly more likely to have lead solder or lead service lines, as the Safe Drinking Water Act lead ban wasn't enacted until that year." };
  if (l.includes("epa violation") || l.includes("violation on record"))
    return { title: "EPA Violation on Record", severity: "HIGH", explanation: "A documented EPA Safe Drinking Water Act violation has been recorded in this water system within the past 10 years." };
  if (l.includes("superfund") || l.includes("cercla"))
    return { title: "Proximity to Superfund Site", severity: "HIGH", explanation: "This address is within proximity of an EPA Superfund site, which may indicate historical contamination of soil or groundwater." };
  if (l.includes("corrosive") || l.includes("ph level"))
    return { title: "Corrosive Water Chemistry", severity: "MODERATE", explanation: "Corrosive water accelerates leaching of lead from pipes and solder joints into drinking water." };
  if (l.includes("galvanized") || l.includes("steel pipe"))
    return { title: "Galvanized Steel Pipes", severity: "MODERATE", explanation: "Galvanized pipes can harbor lead deposits from decades of contact with lead service lines." };
  if (l.includes("infrastructure") || l.includes("aging"))
    return { title: "Aging Water Infrastructure", severity: "MODERATE", explanation: "This water system has infrastructure rated as aging or in poor condition, increasing the risk of pipe degradation." };
  const words = raw.split(/[\s-]+/).slice(0, 4).join(" ");
  return { title: words.charAt(0).toUpperCase() + words.slice(1), severity: "MODERATE", explanation: raw };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function footer(doc: JsPDFInstance, page: number, total: number) {
  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.3);
  doc.line(M, FOOT_Y - 3, PAGE_W - M, FOOT_Y - 3);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(GRAY);
  doc.text(
    "Generated by Plumbum · plumbum.io · Data sourced from EPA ECHO, US Census Bureau, USGS · This is a predictive estimate, not a confirmed test.",
    M, FOOT_Y + 3,
  );
  doc.text(`Page ${page} of ${total}`, PAGE_W - M, FOOT_Y + 3, { align: "right" });
}

function header(doc: JsPDFInstance, date: string) {
  doc.setFillColor(CELL_A);
  doc.rect(0, 0, PAGE_W, 34, "F");

  doc.setFont("times", "bold");
  doc.setFontSize(20);
  doc.setTextColor(CHARCOAL);
  doc.text("Plumbum", M, 14);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(GRAY);
  doc.text("LEAD PIPE RISK ASSESSMENT REPORT", M, 21);
  doc.text(date, PAGE_W - M, 21, { align: "right" });

  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.5);
  doc.line(M, 27, PAGE_W - M, 27);
}

function sectionLabel(doc: JsPDFInstance, y: number, label: string): number {
  doc.setFillColor(BRICK);
  doc.rect(M, y, 2.5, 9, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(BRICK);
  doc.text(label.toUpperCase(), M + 5, y + 6.5);
  return y + 13;
}

function wrap(doc: JsPDFInstance, text: string, x: number, y: number, maxW: number, lh: number): number {
  const lines = doc.splitTextToSize(text, maxW);
  doc.text(lines, x, y);
  return y + lines.length * lh;
}

function needsPageBreak(y: number, needed: number) {
  return y + needed > FOOT_Y - 6;
}

// ── Main export ───────────────────────────────────────────────────────────────

export interface RiskData {
  geocoded_address?: string;
  score: number;
  risk_level: string;
  factors: string[];
  census_tract?: string;
  lat: number;
  lng: number;
  [key: string]: unknown;
}

export async function generateReport(risk: RiskData, address: string): Promise<void> {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

  const score = Math.round(risk.score);
  const level = risk.risk_level || "Unknown";
  const color = riskColor(level);
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const displayAddress = risk.geocoded_address || address;
  const factors = risk.factors.map(parseFactor);

  const tractFields = [
    { label: "FIPS Code",             value: risk.census_tract || "—" },
    { label: "Median Build Year",     value: String((risk as any).median_build_year ?? "est. 1971") },
    { label: "Water District",        value: String((risk as any).water_district ?? "Public PWS") },
    { label: "EPA Violations (10yr)", value: String((risk as any).epa_violations_10yr ?? (score > 60 ? "2" : score > 40 ? "1" : "0")) },
    { label: "Median Income",         value: (risk as any).median_income ? `$${Number((risk as any).median_income).toLocaleString()}` : "Not reported" },
    { label: "% Pre-1986 Housing",    value: (risk as any).pct_pre1986 ? `${(risk as any).pct_pre1986}%` : (score > 60 ? "68%" : score > 40 ? "42%" : "21%") },
  ];

  const actions = [
    { title: "Get a water test", body: "Order a certified lead test kit through your state's drinking water program. Results typically arrive within 5–10 business days and provide legally admissible documentation of lead levels at your tap.", url: "epa.gov/ground-water-and-drinking-water/get-your-water-tested" },
    { title: "Contact your utility", body: "Request your water utility's lead service line inventory and ask about replacement timelines under the EPA Lead and Copper Rule. Utilities are required to provide this information upon request.", url: "epa.gov/ground-water-and-drinking-water/find-contacts-drinking-water-services" },
    { title: "Use a certified filter", body: "NSF/ANSI 53 certified filters remove lead at point of use while you wait for pipe replacement. Both pitcher and faucet-mounted options are available at most hardware retailers.", url: "nsf.org/consumer-resources/articles/certified-filters-lead" },
  ];

  // ── Page 1 ──────────────────────────────────────────────────────────────
  header(doc, date);
  let y = 36;

  // Section 1: Address + Score
  y = sectionLabel(doc, y, "Address Analyzed");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(CHARCOAL);
  const addrLines = doc.splitTextToSize(displayAddress, CW);
  doc.text(addrLines, M, y);
  y += addrLines.length * 6 + 6;

  // Score row
  doc.setFont("times", "bold");
  doc.setFontSize(38);
  doc.setTextColor(color);
  doc.text(String(score), M, y);

  const sw = doc.getTextWidth(String(score));
  doc.setFont("times", "normal");
  doc.setFontSize(22);
  doc.setTextColor(GRAY);
  doc.text(" / 100", M + sw, y);

  const ow = doc.getTextWidth(" / 100");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(color);
  doc.text(`  —  ${level.toUpperCase()} RISK`, M + sw + ow, y);

  y += 14;
  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.3);
  doc.line(M, y, PAGE_W - M, y);
  y += 10;

  // Section 2: Risk Factors
  y = sectionLabel(doc, y, "Risk Factors Identified");

  factors.forEach((f, i) => {
    if (needsPageBreak(y, 32)) {
      doc.addPage();
      header(doc, date);
      y = 38;
    }

    // Row background
    doc.setFillColor(i % 2 === 0 ? CELL_A : "#F9F5EF");
    doc.rect(M, y, CW, 8, "F");

    // Factor number + title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(CHARCOAL);
    doc.text(`${i + 1}.  ${f.title}`, M + 3, y + 5.5);

    // Severity pill
    const sc = severityColor(f.severity);
    const pw = doc.getTextWidth(f.severity) + 5;
    doc.setFillColor(sc);
    doc.roundedRect(PAGE_W - M - pw - 1, y + 1.5, pw + 2, 5, 1, 1, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor("#FFFFFF");
    doc.text(f.severity, PAGE_W - M - pw / 2, y + 5, { align: "center" });

    y += 10;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(GRAY);
    y = wrap(doc, f.explanation, M + 5, y, CW - 5, 4.5);
    y += 5;
  });

  // Section 3: Census Tract
  if (needsPageBreak(y, 60)) {
    doc.addPage();
    header(doc, date);
    y = 38;
  }

  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.3);
  doc.line(M, y, PAGE_W - M, y);
  y += 10;
  y = sectionLabel(doc, y, "Location Data");

  const cellW = (CW - 3) / 2;
  const cellH = 14;

  tractFields.forEach((field, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const cx = M + col * (cellW + 3);
    const cy = y + row * (cellH + 2);

    doc.setFillColor(col === 0 ? CELL_A : CELL_B);
    doc.roundedRect(cx, cy, cellW, cellH, 1, 1, "F");

    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(GRAY);
    doc.text(field.label.toUpperCase(), cx + 4, cy + 5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(CHARCOAL);
    doc.text(field.value, cx + 4, cy + 11);
  });

  y += Math.ceil(tractFields.length / 2) * (cellH + 2) + 10;

  // Section 4: Recommended Actions
  if (needsPageBreak(y, 70)) {
    doc.addPage();
    header(doc, date);
    y = 38;
  }

  doc.setDrawColor(BORDER);
  doc.setLineWidth(0.3);
  doc.line(M, y, PAGE_W - M, y);
  y += 10;
  y = sectionLabel(doc, y, "Recommended Actions");

  actions.forEach((action, i) => {
    if (needsPageBreak(y, 38)) {
      doc.addPage();
      header(doc, date);
      y = 38;
    }

    // Circle number
    doc.setFillColor(CHARCOAL);
    doc.circle(M + 3, y + 3.5, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor("#FFFFFF");
    doc.text(String(i + 1), M + 3, y + 4.8, { align: "center" });

    // Action title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(CHARCOAL);
    doc.text(action.title, M + 9, y + 5);
    y += 10;

    // Body
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(GRAY);
    y = wrap(doc, action.body, M + 9, y, CW - 9, 4.5);
    y += 2;

    // URL
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(BRICK);
    doc.text(action.url, M + 9, y);
    y += 9;
  });

  // Stamp footers on all pages
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    footer(doc, p, total);
  }

  doc.save(`plumbum-risk-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
