/* Generates a formal pediatrician blood-lead-level request letter as a PDF.
   Uses jsPDF loaded from CDN — no npm install required.                     */

interface JsPDFConstructor {
  new (opts: { unit: string; format: string; orientation: string }): JsPDFInstance;
}

interface JsPDFInstance {
  setFont(name: string, style: string): void;
  setFontSize(size: number): void;
  setTextColor(r: number, g: number, b: number): void;
  setDrawColor(r: number, g: number, b: number): void;
  setFillColor(r: number, g: number, b: number): void;
  setLineWidth(w: number): void;
  text(text: string | string[], x: number, y: number, opts?: Record<string, unknown>): void;
  getTextWidth(text: string): number;
  splitTextToSize(text: string, maxWidth: number): string[];
  line(x1: number, y1: number, x2: number, y2: number): void;
  rect(x: number, y: number, w: number, h: number, style?: string): void;
  roundedRect(x: number, y: number, w: number, h: number, rx: number, ry: number, style?: string): void;
  addPage(): void;
  save(filename: string): void;
}

function loadJsPDF(): Promise<JsPDFConstructor> {
  return new Promise((resolve, reject) => {
    const w = window as Window & { jspdf?: { jsPDF: JsPDFConstructor } };
    if (w.jspdf?.jsPDF) { resolve(w.jspdf.jsPDF); return; }
    const script = document.createElement("script");
    script.src = "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
    script.onload = () => {
      const loaded = (window as Window & { jspdf?: { jsPDF: JsPDFConstructor } }).jspdf?.jsPDF;
      if (loaded) resolve(loaded); else reject(new Error("jsPDF failed to initialise"));
    };
    script.onerror = () => reject(new Error("Could not load jsPDF from CDN"));
    document.head.appendChild(script);
  });
}

// ── Palette (matches generateReport.ts) ──────────────────────────────────────
const CHARCOAL = [26, 22, 20] as const;   // #1A1614
const GRAY     = [122, 111, 101] as const; // #7A6F65
const BRICK    = [166, 61, 47] as const;   // #A63D2F
const BORDER   = [214, 207, 200] as const; // #D6CFC8
const BG_LIGHT = [244, 239, 232] as const; // #F4EFE8

const PAGE_W = 210;
const PAGE_H = 297;
const M      = 20; // margin
const CW     = PAGE_W - M * 2;
const FOOT_Y = PAGE_H - 14;

function setColor(doc: JsPDFInstance, rgb: readonly [number, number, number]) {
  doc.setTextColor(rgb[0], rgb[1], rgb[2]);
}
function setDraw(doc: JsPDFInstance, rgb: readonly [number, number, number]) {
  doc.setDrawColor(rgb[0], rgb[1], rgb[2]);
}
function setFill(doc: JsPDFInstance, rgb: readonly [number, number, number]) {
  doc.setFillColor(rgb[0], rgb[1], rgb[2]);
}

function drawFooter(doc: JsPDFInstance) {
  setDraw(doc, BORDER);
  doc.setLineWidth(0.3);
  doc.line(M, FOOT_Y - 3, PAGE_W - M, FOOT_Y - 3);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  setColor(doc, GRAY);
  doc.text(
    "This letter was generated by Plumbum, an open-source civic research tool. It is not a medical diagnosis. Consult your healthcare provider.",
    M,
    FOOT_Y,
    { maxWidth: CW },
  );
}

export interface PediatricianLetterData {
  parentName: string;
  childName: string;
  childDob: string;
  pediatricianName: string;
  address: string;
  score: number;
  riskLevel: string;
  factors: Array<{ name: string; detail: string; score: number; max: number }>;
  censusTract: string;
  pctPre1986: number | null | undefined;
  isPregnant?: boolean;
}

export async function generatePediatricianLetter(data: PediatricianLetterData): Promise<void> {
  const JsPDF = await loadJsPDF();
  const doc = new JsPDF({ unit: "mm", format: "a4", orientation: "portrait" });

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const docStr   = data.pediatricianName.trim()
    ? `Dear ${data.pediatricianName.trim()},`
    : data.isPregnant ? "Dear Obstetrician/Provider," : "To Whom It May Concern,";
  const childStr = data.childName.trim() || "[child name]";
  const dobStr   = data.childDob.trim()  || "[date of birth]";
  const parentStr = data.parentName.trim() || (data.isPregnant ? "[patient name]" : "[parent/guardian name]");
  const pre1986Str = data.pctPre1986 != null
    ? `${data.pctPre1986}%`
    : "a significant percentage";

  // ── Header bar ─────────────────────────────────────────────────────────────
  setFill(doc, CHARCOAL);
  doc.rect(0, 0, PAGE_W, 18, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  setColor(doc, [255, 255, 255]);
  doc.text("Plumbum", M, 11.5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  setColor(doc, [180, 170, 160]);
  doc.text("Lead Pipe Risk Assessment Platform · plumbum.io", M + 22, 11.5);

  // ── Document type label ────────────────────────────────────────────────────
  let y = 30;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  setColor(doc, GRAY);
  doc.text("MEDICAL REQUEST LETTER", M, y);

  // ── Date ──────────────────────────────────────────────────────────────────
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  setColor(doc, CHARCOAL);
  doc.text(today, M, y);

  // ── Salutation ─────────────────────────────────────────────────────────────
  y += 9;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  setColor(doc, CHARCOAL);
  doc.text(docStr, M, y);

  // ── Opening paragraph ──────────────────────────────────────────────────────
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10.5);
  setColor(doc, CHARCOAL);

  const para1 = data.isPregnant 
    ? `I am writing to formally request a blood lead level (BLL) test for myself at my next prenatal visit.`
    : `I am writing to formally request a blood lead level (BLL) test for my child, ${childStr}, date of birth ${dobStr}.`;
  const para1Lines = doc.splitTextToSize(para1, CW);
  doc.text(para1Lines, M, y);
  y += para1Lines.length * 5.5 + 4;

  const para2 = `Our home address is ${data.address}, which has been assessed by Plumbum (plumbum.io), an open-source public health research tool built on data from the EPA Safe Drinking Water Information System and the US Census American Community Survey. This address received a lead pipe risk score of ${data.score} out of 100, classified as ${data.riskLevel}.`;
  const para2Lines = doc.splitTextToSize(para2, CW);
  doc.text(para2Lines, M, y);
  y += para2Lines.length * 5.5 + 4;

  // ── Risk factors intro ─────────────────────────────────────────────────────
  doc.text("The assessment identified the following contributing risk factors:", M, y);
  y += 6;

  // ── Risk factor box ────────────────────────────────────────────────────────
  const factorLines: string[][] = data.factors.map(f => {
    const label = `${f.name} (${f.score}/${f.max}): ${f.detail}`;
    return doc.splitTextToSize(`· ${label}`, CW - 8);
  });
  const boxH = factorLines.reduce((h, ls) => h + ls.length * 5 + 2, 8);

  setFill(doc, BG_LIGHT);
  setDraw(doc, BORDER);
  doc.setLineWidth(0.3);
  doc.roundedRect(M, y, CW, boxH, 2, 2, "FD");

  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  setColor(doc, CHARCOAL);
  for (const ls of factorLines) {
    doc.text(ls, M + 4, y);
    y += ls.length * 5 + 2;
  }
  y += 5;

  // ── Census tract paragraph ─────────────────────────────────────────────────
  const tractPara = `The census tract serving this address (${data.censusTract || "N/A"}) has ${pre1986Str} of housing units built before 1986, the year the federal government banned new lead service line installations.`;
  doc.setFontSize(10.5);
  const tractLines = doc.splitTextToSize(tractPara, CW);
  doc.text(tractLines, M, y);
  y += tractLines.length * 5.5 + 4;

  // ── CDC / AAP / ACOG paragraph ─────────────────────────────────────────────
  const cdcPara = data.isPregnant
    ? "The CDC states there is no safe level of lead exposure during pregnancy, as it can cause miscarriage, premature birth, and permanent harm to fetal brain development. The American College of Obstetricians and Gynecologists (ACOG) recommends blood lead testing for pregnant individuals with identified environmental risk factors, including residence in pre-1978 housing or areas with known lead pipe infrastructure."
    : "The CDC states there is no safe level of lead exposure in children. The American Academy of Pediatrics recommends blood lead testing for children with environmental risk factors including residence in pre-1978 housing or areas with known lead pipe infrastructure.";
  const cdcLines = doc.splitTextToSize(cdcPara, CW);
  doc.text(cdcLines, M, y);
  y += cdcLines.length * 5.5 + 4;

  // ── Closing ───────────────────────────────────────────────────────────────
  const closingPara = "I respectfully request that a blood lead level test be ordered at our next visit. I am happy to discuss this assessment further.";
  const closingLines = doc.splitTextToSize(closingPara, CW);
  doc.text(closingLines, M, y);
  y += closingLines.length * 5.5 + 8;

  // ── Signature block ────────────────────────────────────────────────────────
  doc.text("Sincerely,", M, y);
  y += 10;

  if (parentStr !== "[parent/guardian name]" && parentStr !== "[patient name]") {
    doc.setFont("helvetica", "bold");
    doc.text(parentStr, M, y);
    doc.setFont("helvetica", "normal");
    y += 6;
  }

  // Signature line
  setDraw(doc, BORDER);
  doc.setLineWidth(0.4);
  doc.line(M, y, M + 60, y);
  y += 8;

  // ── Citations box ──────────────────────────────────────────────────────────
  setFill(doc, [248, 244, 240]);
  setDraw(doc, BORDER);
  doc.setLineWidth(0.3);
  doc.roundedRect(M, y, CW, 22, 2, 2, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  setColor(doc, GRAY);
  doc.text("DATA SOURCES & METHODOLOGY", M + 4, y + 5);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  setColor(doc, CHARCOAL);
  doc.text("Plumbum methodology and data sources: plumbum.io/methodology", M + 4, y + 11);
  doc.text("Plumbum arXiv preprint: arxiv.org/abs/plumbum", M + 4, y + 17);

  // ── Footer ─────────────────────────────────────────────────────────────────
  drawFooter(doc);

  doc.save(`plumbum-pediatrician-letter-${Date.now()}.pdf`);
}
